### ISSUE TITLE
First release of the `Our Handbook` handbook

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/our-handbook-user-guide#2]
## Basic Setup
- [ ] GitHub + Jupyter book setup (#8)

## Sections
- [ ] Welcome 
   - [ ] Tour of materials (template + metahandbook, deployed + github versions)
- [ ] How to use the template
    - [ ] Quickstart guide
    - [ ] Getting started
    - [ ] Preparing for an away day
        - [ ] Template schedule (maybe a 1 and a 2 day version) to send out to attendees
          - [ ] DAY 1:
            - [ ] photo shoot (group/individual photos)
            - [ ] tour of the book + the repo (contributing guidelines/code of conduct)
            - [ ] look at examples for inspiration
            - [ ] brainstorm sections for your book that aren't already on the list
            - [ ] delete sections/add new sections from existing list
            - [ ] prioritise new list of sections
            - [ ] split up sections (sometimes individual/sometimes pairs/sometimes the whole group) - make note in a GitHub issue/checklist.
            - [ ] free-writing
            - [ ] write content for a joint section together, following one of the writing exercises
            - [ ] split up to write on your own/in pairs/in groups
            - [ ] leave plenty of time for merging pull requests
            - [ ] Put your book online
          - [ ] DAY 2
            - [ ] free-writing
            - [ ] jointly write content with writing exercise
            - [ ] individual/pair/small group editing + writing
            - [ ] merging pull requests
            - [ ] new version online
            - [ ] ensure that you have maintainers locked down
            - [ ] make a plan for any further edits (when by/who, and when to review together - group meeting?)
        - [ ] A GitHub savvy person should volunteer to manage the repository - link to training materials.
          - [ ] Make the issue labels and a Milestone
          - [ ] Make sure everyone has GitHub accounts and add them as collaborators
          - [ ] Maybe hold a GitHub intro/training session in advance of the main handbook day if you need to
          - [ ] Make sure everyone has a good text editor with a working terminal
          - [ ] Delete Our Handbook contributors
          - [ ] (Optional) Edit/add issue templates
    - [ ] Editing the template
      - [ ] Lead handbook-er
        - [ ] Remove the sections from the TOC for things that you are going to do. Remove markdown for things that you aren't going to do.
      - [ ] Basics (everyone needs to know)
        - [ ] Jupyter book syntax
        - [ ] Template specifics (FIXMEs, comments, options, writing exercises)
        - [ ] How to edit (GitHub flow: Make an issue, comment on the issue, fork the repo, make a WIP PR, edit, preview/local serve, commit, ask for review/make PR "ready to review", merge PR).
        - [ ] Advice for editing
           - [ ] Don't work on the same bits all at once, if you want to avoid merge conflicts.
           - [ ] VS code > Pycharm for jupyter book syntax
    - [ ] Deploying your handbook online 
    - [ ] Actioning your roadmap, embodying your values, etc
- [ ] Maintaining the handbook
   - [ ] On-boarding a new team member
   - [ ] Review as a team
   - [ ] Review in one-to-ones
- [ ] Contributing to the project
   - [ ] Contributing to the template
   - [ ] Contributing to the handbook

**Comment by NatalieZelenka** [comment]
This is an old issue that lists everything that I could think of that might want to be in the the prototype of `Our Handbook`, before it was planned to co-create it at the E-life sprint. We'll make a new checklist/plan at the sprint together.
